syntax enable
colorscheme kolor
set tags=tags;/
set t_Co=256
set nocompatible
syntax on
set cursorline
set cursorcolumn
set enc=utf-8
set fileencodings=utf-8
set termencoding=utf-8
set nobackup
set encoding=utf-8
set autoindent
set cindent
set shiftwidth=4
set tabstop=4
set expandtab
set softtabstop=4
set listchars=tab:->,trail:-
set fileformats=unix
set backspace=indent,eol,start
set history=50
set showcmd
set number
set incsearch
set hlsearch
set wildmenu
filetype plugin indent on
set cino=:0,l1,g0,p0,t0
"let g:ycm_global_ycm_extra_conf='~/.vim/plugin/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py'
