all:
	make -C ./get_mq_stat clean
	make -C ./get_mq_stat
	make -C ./so_loader clean
	make -C ./so_loader
	make -C ./mcp_trace clean
	make -C ./mcp_trace
	make -C ./get_so_info clean
	make -C ./get_so_info

clean:
	make -C ./get_mq_stat clean
	make -C ./so_loader clean
	make -C ./mcp_trace clean
	make -C ./get_so_info clean

